test_files/mock_imports.py: error: Source file found twice under different module names: "mock_imports" and "test_files.mock_imports"
test_files/mock_imports.py: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#mapping-file-paths-to-modules for more info
test_files/mock_imports.py: note: Common resolutions include: a) adding `__init__.py` somewhere, b) using `--explicit-package-bases` or adjusting MYPYPATH
Found 1 error in 1 file (errors prevented further checking)
